version: "3.5"
x-environment:
  &QUICKSTART_ENVIRONMENT # These are read from .env file. The values in the .env file maybe overriden by shell envvars
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET: ${PLAID_SECRET}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  PLAID_ENV: ${PLAID_ENV}
services:
  node:
    networks:
      - "plaid-quickstart"
    depends_on:
      - "frontend"
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports: ["8000:8000"]
    environment:
      <<: *QUICKSTART_ENVIRONMENT
  frontend:
    environment:
      - REACT_APP_API_HOST
    networks:
      - "plaid-quickstart"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports: ["3000:3000"]
networks:
  quickstart:
    name: plaid-quickstart
